#!/usr/bin/env python3
"""
P8.1 gate G0 (docs/phase8_registration.md section 3): the C++ v6 path reproduces
the frozen v6 artifacts at rtol 1e-9 (abs 1e-12 for zeros), with the
scripts/reproduce_check.py comparison rule (numbers by math.isclose, strings
exactly, same columns and shape).

Checks, each regenerated through the protected v6 code with only the worker
engine replaced (scripts/phase8/v6_backend.py):
  G0-cal   outputs/phase7/calibration_v6_rows.csv         (93 rows, v6 params)
  G0-hold  outputs/phase7/holdout_icao_validation_v6.csv   (87 rows) and
           outputs/phase7/holdout_icao_validation_summary_v6.csv
  G0-AE3   outputs/design_point_summary_v5.csv (the frozen AE3 design-point
           artifact: v5 calibration, Jet-A1, every LTO mode, incl. p5 and
           specific thrust), regenerated by the C++ engine in process.
The Python backend is run on G0-cal and G0-hold as well (A0 reproducibility
today); its result is reported but is not the gate.

Outputs (write-once): outputs/phase8/g0/*.csv (regenerated tables) and
outputs/phase8/g0_parity.json (verdict, per-column max relative difference).
Usage: .venv/bin/python scripts/phase8/g0_parity.py [--workers 6]
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import math
import platform
import subprocess
import sys
import time
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts" / "optimization"))
sys.path.insert(0, str(ROOT / "scripts" / "phase8"))

import lto_v5 as v5  # noqa: E402
import lto_v6  # noqa: E402
from v6_backend import make_model_v6  # noqa: E402

OUT_DIR = ROOT / "outputs" / "phase8" / "g0"
OUT_JSON = ROOT / "outputs" / "phase8" / "g0_parity.json"
RTOL, ATOL = 1e-9, 1e-12
FROZEN = {
    "cal": ROOT / "outputs" / "phase7" / "calibration_v6_rows.csv",
    "hold": ROOT / "outputs" / "phase7" / "holdout_icao_validation_v6.csv",
    "hold_summary": ROOT / "outputs" / "phase7" / "holdout_icao_validation_summary_v6.csv",
    "ae3": ROOT / "outputs" / "design_point_summary_v5.csv",
}


def compare(frozen: Path, new: Path) -> dict:
    """reproduce_check.compare, plus the per-column maximum relative difference."""
    a, b = pd.read_csv(frozen), pd.read_csv(new)
    res = {"frozen": str(frozen.relative_to(ROOT)), "new": str(new.relative_to(ROOT)),
           "rows": int(a.shape[0]), "columns": {}, "match": True}
    if list(a.columns) != list(b.columns) or a.shape != b.shape:
        res.update(match=False, problem=f"shape/columns {a.shape} vs {b.shape}")
        return res
    for c in a.columns:
        if pd.api.types.is_numeric_dtype(a[c]) and pd.api.types.is_numeric_dtype(b[c]):
            worst, ok = 0.0, True
            for x, y in zip(a[c], b[c]):
                x, y = float(x), float(y)
                if math.isnan(x) and math.isnan(y):
                    continue
                if not math.isclose(x, y, rel_tol=RTOL, abs_tol=ATOL):
                    ok = False
                if x != 0 and math.isfinite(x) and math.isfinite(y):
                    worst = max(worst, abs(y - x) / abs(x))
                elif x != y:
                    worst = max(worst, abs(y - x))
            res["columns"][c] = {"numeric": True, "max_rel_diff": worst, "match": ok}
        else:
            ok = a[c].fillna("").astype(str).equals(b[c].fillna("").astype(str))
            res["columns"][c] = {"numeric": False, "match": bool(ok)}
        res["match"] &= res["columns"][c]["match"]
    return res


def regenerate(backend: str, n_workers: int, tag: str) -> dict:
    reg6 = lto_v6.load_registration_v6()
    base = lto_v6.base_registration(reg6)
    split = v5.load_split()
    fitted = json.loads((ROOT / "outputs" / "phase7" / "calibration_v6.json").read_text())
    rows = v5.calibration_rows(split)
    cal = v5.calibration_rows(split)
    held = v5.attach_groups(v5.load_rows(split["heldout_records"], with_targets=True),
                            split["heldout_groups"])
    model = make_model_v6(backend, n_workers)
    t0 = time.perf_counter()
    try:
        pred_cal = model.predict(fitted["params"], rows)
        model.guess.clear()          # held-out rows are scored by a fresh model in run_holdout
        pred_hold = model.predict(fitted["params"], held)
    finally:
        model.close()
    wall = time.perf_counter() - t0
    rows_out = rows.drop(columns=["CO (g/kg)", "HC (g/kg)", "NOx (g/kg)"]).join(pred_cal)
    df, summary, _ = v5.holdout_tables(base, cal, held, pred_hold)
    paths = {"cal": OUT_DIR / f"calibration_v6_rows_{tag}.csv",
             "hold": OUT_DIR / f"holdout_icao_validation_v6_{tag}.csv",
             "hold_summary": OUT_DIR / f"holdout_icao_validation_summary_v6_{tag}.csv"}
    rows_out.to_csv(paths["cal"], index=False)
    df.to_csv(paths["hold"], index=False)
    summary.to_csv(paths["hold_summary"], index=False)
    return {"paths": paths, "wall_s": wall}


def regenerate_ae3_design_point(tag: str) -> Path:
    """design_point_summary.py --v5 with the C++ engine (same rows, same columns)."""
    from integrated_engine import FUEL_LIBRARY
    from simulation.catjet_backend import CppEngine
    reg, split = v5.load_registration(), v5.load_split()
    fit = json.loads(v5.V5_FIT.read_text())
    fixed = reg["fixed_central"]
    ae3 = v5.load_rows(["02P23RR126"], with_targets=True)
    with contextlib.redirect_stdout(io.StringIO()):
        engine = CppEngine(nox_fit_exclude_models=set(split["heldout_models"]))
    engine.compressor.eta_c = fixed["eta_compressor"]
    engine.turbine_design["eta_polytropic"] = fixed["eta_turbine_polytropic"]
    out_rows = []
    for _, r in ae3.iterrows():
        x = v5.MODE_X[r["Mode"]]
        engine.design_point.update(v5.mode_state(fit["params"], fixed, r["Pressure Ratio"],
                                                 r["Bypass Ratio"], r["Rated Thrust (kN)"], x))
        res = engine.run_at_thrust(x * r["Rated Thrust (kN)"], FUEL_LIBRARY["Jet-A1"],
                                   combustor_efficiency=fixed["eta_b"][r["Mode"]])
        p = res["performance"]
        out_rows.append({
            "calibration": v5.V5_FIT.name, "mode": r["Mode"],
            "component_config": "turbine=analytic, nozzle=analytic; single-zone equilibrium combustor",
            "target_thrust_kN": x * r["Rated Thrust (kN)"], "thrust_kN": p["thrust_kN"],
            "phi_solved": res["thrust_match"]["phi"], "eta_b": fixed["eta_b"][r["Mode"]],
            "pi_c": engine.design_point["pi_c"], "fpr": engine.design_point["fpr"],
            "mass_flow_core_kg_s": engine.design_point["mass_flow_core"],
            "T3_K": res["compressor"]["T_out"], "T4_K": res["combustor"]["T_out"],
            "T5_K": res["turbine"]["T"], "p5_bar": res["turbine"]["p"] / 1e5,
            "fuel_flow_kg_s": p["fuel_mass_flow"],
            "icao_fuel_flow_kg_s": float(r["Fuel Flow (kg/s)"]),
            "fuel_flow_rel_err_pct": 100 * (p["fuel_mass_flow"] / r["Fuel Flow (kg/s)"] - 1),
            "thrust_core_kN": p["thrust_core_kN"], "thrust_bypass_kN": p["thrust_bypass_kN"],
            "TSFC_mg_per_Ns": p["tsfc_mg_per_Ns"],
            "specific_thrust_Ns_kg": p["specific_thrust_Ns_kg"],
            "total_air_mass_flow_kg_s": p["total_air_mass_flow"],
            "NOx_corr_g_s": res["emissions"]["NOx_g_s"],
        })
    path = OUT_DIR / f"design_point_summary_v5_{tag}.csv"
    pd.DataFrame(out_rows).to_csv(path, index=False)
    return path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workers", type=int, default=6)
    a = ap.parse_args()
    if OUT_JSON.exists() or OUT_DIR.exists():
        print("G0 outputs exist; refusing to overwrite")
        return 1
    OUT_DIR.mkdir(parents=True)
    sha = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True,
                         check=True).stdout.strip()
    dirty = subprocess.run(["git", "status", "--porcelain", "--", "cpp", "simulation", "scripts"],
                           cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
    runs = {}
    for backend in ("cpp", "python"):
        g = regenerate(backend, a.workers, backend)
        runs[backend] = {"wall_s": g["wall_s"],
                         "checks": {k: compare(FROZEN[k], p) for k, p in g["paths"].items()}}
    ae3 = regenerate_ae3_design_point("cpp")
    runs["cpp"]["checks"]["ae3"] = compare(FROZEN["ae3"], ae3)
    g0 = all(c["match"] for c in runs["cpp"]["checks"].values())
    doc = {
        "gate": "G0 (docs/phase8_registration.md section 3)",
        "verdict": "PASS" if g0 else "FAIL",
        "rule": f"math.isclose(rel_tol={RTOL}, abs_tol={ATOL}) per numeric cell; strings exact; same shape/columns",
        "commit": sha, "uncommitted_source_changes": dirty or None,
        "machine": platform.platform(), "python": platform.python_version(),
        "backends": runs,
        "note": "python backend = A0 reproducibility of the frozen artifacts today (reported, not the gate)",
    }
    OUT_JSON.write_text(json.dumps(doc, indent=2, default=str) + "\n")
    for be, r in runs.items():
        for k, c in r["checks"].items():
            worst = max((v.get("max_rel_diff", 0.0) for v in c["columns"].values()), default=0.0)
            bad = [col for col, v in c["columns"].items() if not v["match"]]
            print(f"{be:6s} {k:12s} rows {c['rows']:3d}  match={c['match']}  max rel diff {worst:.2e}  {bad or ''}")
    print(f"G0: {doc['verdict']}")
    return 0 if g0 else 1


if __name__ == "__main__":
    sys.exit(main())
