#!/usr/bin/env python3
"""One-shot, integrity-first recovery of stages f-i after the stage-f JSON serialization crash.

Dry-run (default) verifies the consumed original attempt read-only and prints the intended actions.
``--run`` executes exactly once: it resumes the identical hashed score reservation, byte-compares every
existing score output against exactly regenerated bytes, then runs the actual pipeline stages g, h and i
into a NEW metadata directory. Nothing here changes a metric, threshold, model, selection or registration.
"""
from __future__ import annotations

import argparse
import contextlib
import copy
import hashlib
import json
import os
import subprocess
import sys
import time
import traceback
import uuid
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

SOURCE_COMMIT = "0d16bcc245e93172aa4b3749bccc877727ce950c"
BRANCH = "pc-recovery-20261005"
OLD_METADATA = "outputs/phase8/pc_python_pipeline"
NEW_METADATA = "outputs/phase8/pc_python_recovery_20261005"
SAF_REGISTRATION = "docs/phase8_saf_surrogate_registration.json"
FIX_PATH = "scripts/phase8/saf_surrogate/registration.py"
SELF_PATH = "scripts/phase8/pc_recover_f_to_i.py"
THREAD_ENV = ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "VECLIB_MAXIMUM_THREADS")

# The only reviewed source edit: byte-exact replacement applied to the original (source commit) file.
AUTHORIZED_EDITS = {FIX_PATH: ((
    'def json_bytes(value):\n'
    '    return (json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\\n").encode()\n',
    'def _native(value):\n'
    '    """NumPy scalars (e.g. numpy.bool_) become plain Python values; everything else stays rejected."""\n'
    '    import sys\n'
    '    numpy = sys.modules.get("numpy")\n'
    '    if numpy is not None and isinstance(value, numpy.generic):\n'
    '        return value.item()\n'
    '    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")\n'
    '\n'
    '\n'
    'def json_bytes(value):\n'
    '    return (json.dumps(value, indent=2, sort_keys=True, allow_nan=False, default=_native) + "\\n").encode()\n'),)}
ALLOWED_CHANGES = frozenset({FIX_PATH, SELF_PATH, "tests/test_phase8_pc_recovery.py", "docs/FIXES.md", "docs/plan.md"})

# Independently captured immutable hashes of the consumed attempt (paths relative to the SAF attempt).
PINNED = {
    "score_reservation.json": "d03bfdc00d6383ff32787420ef64413a73b38c5f0a32b565340077f0ca937924",
    "predictions_freeze.json": "f8973dd677d667cc087274221beba43b14e7b2c450869805b39a775122a2dbbb",
    "selection.json": "6c76f8457fc588fd5da68715b5a391e27cf520a782bb48b903cc80466f1abb51",
    "test_metrics.json": "df550d78e0e781ae5a1b82f66e37326e94b10c1113f93789ee83c83ddc7422b6",
    "ranking_metrics.json": "26ef11f4af2554f6cfd3a458f9f34838563819de25b8148ac85e2611f3a83564",
}
SEALED_TARGETS = ("sealed/test_teacher_rows.csv", "sealed/test_teacher_species.npz", "sealed/ranking_teacher_rows.csv",
                  "sealed/ranking_teacher_species.npz", "sealed/named_central_full_state.csv", "sealed/named_central_species.npz")
# Outputs that only a completed f/h would create; their presence means this is not the crashed state.
MUST_BE_ABSENT = ("named_metrics.json", "sole_score_summary.json", "ranking_predictions.csv", "test_predictions.csv",
                  "named_predictions.csv", "all_candidate_diagnostic_metrics.csv", "per_seed_metrics.csv",
                  "deployment_receipt.json", "timing.json", "pc_timing_break_even.json", "report.json",
                  "mlx_gpu_timing.json", "pc_pipeline_provenance.json", "study_predictions.csv", "study_bands.csv",
                  "study_topten.json")
CARRIED = "bcde"
NEW_STAGES = "afghi"
OWNER_CMDLINES = ("pc_pipeline.py", "pc_recover_f_to_i.py")


class RecoveryError(RuntimeError):
    pass


def need(condition, message):
    if not condition:
        raise RecoveryError(message)


def sha256(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def read_json(path):
    return json.loads(Path(path).read_text())


def fingerprint(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()).hexdigest()


def utc():
    return datetime.now(timezone.utc).isoformat()


class Layout:
    """Fixed locations of the consumed attempt and the new recovery metadata."""

    def __init__(self, root, *, old_metadata=OLD_METADATA, new_metadata=NEW_METADATA, registration=None):
        self.root = Path(root).resolve()
        self.old = self.root / old_metadata
        self.new = self.root / new_metadata
        reg = registration if registration is not None else read_json(self.root / SAF_REGISTRATION)
        self.registration = reg
        self.saf = self.root / reg["artifact_root"]

    def relative(self, path):
        return Path(path).resolve().relative_to(self.root).as_posix()


# --------------------------------------------------------------------------- read-only verification

def tree_manifest(folder):
    """sha256/size of every regular file; any symlink under the tree is rejected."""
    folder = Path(folder)
    need(folder.is_dir() and not folder.is_symlink(), f"Missing or symlinked tree: {folder}")
    result = {}
    for directory, dirs, files in os.walk(folder, followlinks=False):
        for name in (*dirs, *files):
            need(not os.path.islink(os.path.join(directory, name)), f"Symlink in consumed tree: {name}")
        for name in files:
            path = Path(directory) / name
            result[path.relative_to(folder).as_posix()] = {"sha256": sha256(path), "size": path.stat().st_size}
    return result


def verify_unchanged(folder, manifest, *, exact):
    """Original bytes and names survive; ``exact`` also forbids any added file."""
    current = tree_manifest(folder)
    missing = sorted(set(manifest) - set(current))
    changed = sorted(name for name in manifest if name in current and current[name] != manifest[name])
    added = sorted(set(current) - set(manifest))
    need(not missing and not changed, f"Consumed files changed or vanished: {(missing + changed)[:5]}")
    need(not (exact and added), f"Unexpected files added to the consumed tree: {added[:5]}")
    return {"files": len(manifest), "added": added}


def active_owner_processes(proc="/proc", *, own_pid=None):
    """Other live pipeline/recovery interpreters; argv-based so a shell that merely names the script is ignored."""
    own_pid = os.getpid() if own_pid is None else own_pid
    found = []
    proc = Path(proc)
    if not proc.is_dir():
        return found
    for entry in proc.iterdir():
        if not entry.name.isdigit() or int(entry.name) == own_pid:
            continue
        try:
            argv = (entry / "cmdline").read_bytes().split(b"\0")
        except OSError:
            continue
        argv = [part.decode(errors="replace") for part in argv if part]
        if argv and Path(argv[0]).name.startswith("python") and any(
                Path(part).name in OWNER_CMDLINES for part in argv[1:3]):
            found.append(int(entry.name))
    return found


def verify_sources(old_sources, new_sources, *, old_bytes, edits=AUTHORIZED_EDITS, self_path=SELF_PATH):
    """Only the reviewed fix (exact content) and this additive script may differ from the original snapshot."""
    added = sorted(set(new_sources) - set(old_sources))
    removed = sorted(set(old_sources) - set(new_sources))
    changed = sorted(name for name in old_sources if name in new_sources and old_sources[name] != new_sources[name])
    need(added == [self_path], f"Source additions other than the recovery script: {added}")
    need(not removed, f"Source files removed since the original snapshot: {removed}")
    need(changed == sorted(edits), f"Unauthorized source drift: {changed}")
    for name, replacements in edits.items():
        original = old_bytes(name)
        need(sha256_bytes(original) == old_sources[name], f"Source commit content differs from the recorded snapshot: {name}")
        expected = original
        for before, after in replacements:
            need(expected.count(before.encode()) == 1, f"Authorized edit anchor is not unique: {name}")
            expected = expected.replace(before.encode(), after.encode())
        need(sha256_bytes(expected) == new_sources[name], f"{name} is not exactly the authorized serialization fix")
    return {"added": added, "changed": changed, "removed": removed,
            "mapping": {name: {"original_sha256": old_sources[name], "current_sha256": new_sources[name]} for name in changed},
            "original_sources_sha256": fingerprint(old_sources), "current_sources_sha256": fingerprint(new_sources)}


def checked_git(root, *args):
    result = subprocess.run(["git", *args], cwd=root, capture_output=True, text=True)
    if result.returncode:
        raise RecoveryError(f"git {' '.join(args[:2])} failed: {result.stderr.strip()}")
    return result.stdout.strip()


def git_blob(root, commit, path):
    result = subprocess.run(["git", "show", f"{commit}:{path}"], cwd=root, capture_output=True)
    need(result.returncode == 0, f"Source commit does not contain {path}")
    return result.stdout


def verify_git(root, *, git=checked_git, source_commit=SOURCE_COMMIT, branch=BRANCH, allowed=ALLOWED_CHANGES):
    """Known source commit; every change since it is on the exact authorized file list."""
    need(git(root, "cat-file", "-t", source_commit) == "commit", "Known source commit is absent")
    head = git(root, "rev-parse", "HEAD")
    try:
        git(root, "merge-base", "--is-ancestor", source_commit, "HEAD")
    except RecoveryError:
        raise RecoveryError("HEAD does not descend from the known source commit") from None
    changed = set(git(root, "diff", "--name-only", source_commit).splitlines())
    untracked = {name for name in git(root, "ls-files", "--others", "--exclude-standard").splitlines()
                 if not name.startswith("outputs/")}
    unauthorized = sorted((changed | untracked) - set(allowed))
    need(not unauthorized, f"Changes outside the authorized file list: {unauthorized[:8]}")
    blockers = []
    if git(root, "branch", "--show-current") != branch:
        blockers.append(f"not on branch {branch}")
    if git(root, "status", "--porcelain", "--untracked-files=no"):
        blockers.append("tracked changes are uncommitted; commit the authorized files first")
    if git(root, "diff", "--cached", "--name-only"):
        blockers.append("staged files present (publication refuses them)")
    return {"head": head, "source_commit": source_commit, "changed_since_source": sorted(changed),
            "untracked_outside_outputs": sorted(untracked), "run_blockers": blockers}


def _owned(root, name):
    relative = Path(name)
    need(not relative.is_absolute() and ".." not in relative.parts, f"Escaped path: {name}")
    path = root / relative
    need(not path.is_symlink() and path.resolve().is_relative_to(root) and path.is_file(), f"Missing/symlinked/escaped file: {name}")
    return path


def verify_original(layout, *, pins=None, validate_checkpoint=None, verify_artifacts=None):
    """Integrity of the consumed attempt; opens no score/metric content."""
    pins = PINNED if pins is None else pins
    if validate_checkpoint is None or verify_artifacts is None:
        from scripts.pc_pipeline import validate_checkpoint as default_checkpoint
        from scripts.phase8.saf_surrogate.registration import verify_artifacts as default_artifacts
        validate_checkpoint, verify_artifacts = validate_checkpoint or default_checkpoint, verify_artifacts or default_artifacts
    root, saf, old = layout.root, layout.saf, layout.old
    need(old.is_dir() and not old.is_symlink() and saf.is_dir() and not saf.is_symlink(), "Original attempt directories are missing")
    need(not layout.new.exists(), "A recovery attempt already exists; recovery is one-shot")
    for name in ("owner.json", "stage_owner.json", "publication_intent.json", "latest_terminal.json"):
        need(not (old / name).exists(), f"Active or unexpected owner record in the original metadata: {name}")
    need(not active_owner_processes(), "Another pipeline/recovery process is active")
    old_manifest, saf_manifest = tree_manifest(old), tree_manifest(saf)
    for name in MUST_BE_ABSENT:
        need(name not in saf_manifest, f"Unexpected scientific output exists: {name}")
    from scripts.pc_pipeline import scientific_outputs
    need(not scientific_outputs(root)["nozzle"].exists(), "Nozzle output already exists")
    # Stage state: a-e complete, f consumed without a receipt, nothing later.
    checkpoints = old / "checkpoints"
    config_sha = fingerprint(read_json(old / "config.json"))
    receipts = {}
    for letter in "abcde":
        receipts[letter] = validate_checkpoint(root, read_json(checkpoints / f"{letter}.json"), config_sha)
    need((checkpoints / "f.started.json").is_file() and not (checkpoints / "f.json").exists(), "Stage f is not in the crashed state")
    for letter in "ghi":
        need(not (checkpoints / f"{letter}.json").exists() and not (checkpoints / f"{letter}.started.json").exists(),
             f"Stage {letter} already started")
    terminal = read_json(old / "runs/f/terminal.json")
    need(terminal.get("status") == "ERROR" and any("not JSON serializable" in e for e in terminal.get("errors", [])),
         "Original stage f did not end with the diagnosed serialization error")
    # Immutable pins and the reservation.
    pinned = {}
    for name, expected in pins.items():
        need(sha256(_owned(root, layout.relative(saf / name))) == expected, f"Pinned artifact changed: {name}")
        pinned[name] = expected
    reservation = read_json(saf / "score_reservation.json")
    reg_sha = sha256(root / SAF_REGISTRATION)
    need(reservation["registration_sha256"] == reg_sha, "Reservation registration differs")
    need(reservation["predictions_freeze_sha256"] == pins["predictions_freeze.json"]
         and reservation["selection_sha256"] == pins["selection.json"], "Reservation does not bind the pinned freeze/selection")
    expected_targets = {layout.relative(saf / name) for name in SEALED_TARGETS} | set(layout.registration["sole_score"]["named_paths"])
    need(set(reservation["targets"]) == expected_targets, "Reservation target set differs from the registered targets")
    for name, expected in reservation["targets"].items():
        need(sha256(_owned(root, name)) == expected, f"Reservation target changed: {name}")
    frozen = read_json(saf / "predictions_freeze.json")
    need(len(frozen["predictions"]) == 72 and len(frozen["weights"]) == 24, "Frozen prediction/weight counts differ")
    for key in ("predictions", "weights", "inputs"):
        verify_artifacts(saf, frozen[key])
    need(frozen["selection_sha256"] == pins["selection.json"] and frozen["registration_sha256"] == reg_sha
         and frozen["validation_sha256"] == sha256(saf / "validation.json"), "Prediction freeze bindings changed")
    # Identity: reservation, f reservation and the completed d/e producers all agree and match the source snapshot.
    identity = reservation["identity"]
    old_sources = read_json(old / "scientific_sources.json")
    need(identity["git_head"] == SOURCE_COMMIT and identity["registration_sha256"] == reg_sha, "Foreign original identity")
    need(read_json(old / "runs/f/reservation.json")["identity"] == identity, "Original f lease identity differs")
    for letter in "de":
        need(read_json(old / f"runs/{letter}/terminal.json")["identity"] == identity, f"Original {letter} producer identity differs")
    simulator = identity["simulator"]
    need(fingerprint(simulator) == identity["simulator_identity_sha256"] and simulator["source_hashes"] == old_sources
         and identity["source_hashes"] == old_sources, "Original identity does not match the recorded source snapshot")
    for name in ("generation_terminal.json", "product.json"):
        need(read_json(saf / name).get("simulator_identity_sha256") == identity["simulator_identity_sha256"],
             f"{name} was produced by another simulator identity")
    started = datetime.fromisoformat(read_json(checkpoints / "f.started.json")["started_utc"])
    spent = (datetime.fromisoformat(terminal["ended_utc"]) - started).total_seconds()
    need(spent > 0, "Original stage f elapsed time is not positive")
    return {"config_sha256": config_sha, "checkpoints": {k: v["config_sha256"] for k, v in receipts.items()},
            "pinned": pinned, "reservation_targets": len(reservation["targets"]), "frozen_predictions": 72,
            "frozen_weights": 24, "identity": identity, "reservation": reservation, "old_sources": old_sources,
            "original_f_attempt_seconds": spent, "old_manifest": old_manifest, "saf_manifest": saf_manifest}


def verify_all(root, *, new_sources=None, old_bytes=None, git=checked_git, pins=None):
    layout = Layout(root)
    original = verify_original(layout, pins=pins)
    if new_sources is None:
        from scripts.phase8.pc_python_runtime import source_hashes
        new_sources = source_hashes(layout.root)
    bridge = verify_sources(original["old_sources"], new_sources,
                            old_bytes=old_bytes or (lambda name: git_blob(layout.root, SOURCE_COMMIT, name)))
    return layout, original, bridge, verify_git(layout.root, git=git), new_sources


def describe(layout, original, bridge, git_info):
    """Verification summary and intended actions; deliberately free of any score content."""
    return {"mode": "dry-run", "status": "VERIFIED", "source_commit": SOURCE_COMMIT, "head": git_info["head"],
            "run_ready": not git_info["run_blockers"], "run_blockers": git_info["run_blockers"],
            "original_metadata": layout.relative(layout.old), "saf_attempt": layout.relative(layout.saf),
            "new_metadata_would_be": layout.relative(layout.new), "new_metadata_exists": layout.new.exists(),
            "original_config_sha256": original["config_sha256"], "verified_checkpoints": sorted(original["checkpoints"]),
            "pinned_artifacts": original["pinned"], "reservation_targets_verified": original["reservation_targets"],
            "frozen_predictions_verified": original["frozen_predictions"], "frozen_weights_verified": original["frozen_weights"],
            "original_identity_sha256": fingerprint(original["identity"]),
            "original_simulator_identity_sha256": original["identity"]["simulator_identity_sha256"],
            "original_metadata_files": len(original["old_manifest"]), "preexisting_saf_files": len(original["saf_manifest"]),
            "source_bridge": {key: bridge[key] for key in ("added", "changed", "removed", "original_sources_sha256",
                                                          "current_sources_sha256")},
            "changed_since_source_commit": git_info["changed_since_source"],
            "intended_actions": [
                "exclusively create the new metadata directory and the durable consumed marker (any later --run refuses)",
                "write the recovery record, source mapping and preexisting-file manifests; carry original b-e receipts and d/e producer proofs byte-identically",
                "stage a: record the NEW source snapshot and environment",
                "stage f: resume the identical reservation; score_all must regenerate existing outputs byte-for-byte or stop; no new reservation, prediction or weight is written",
                "stages g, h, i via the existing ScientificWorkflow/publish_outputs with the verified source bridge",
                "re-verify the original metadata tree and preexisting SAF files are byte-identical",
            ]}


# --------------------------------------------------------------------------- exact score resume

class ExactResume:
    """Writer adapter for score_all: existing files must match regenerated bytes; new files are held until all do."""

    def __init__(self, saf):
        self.saf = Path(saf).resolve()
        self.compared, self.pending = {}, {}

    def write(self, path, value):
        from scripts.phase8.saf_surrogate.registration import json_bytes
        data = value if isinstance(value, bytes) else json_bytes(value)
        path = Path(path)
        need(not path.is_symlink(), f"Symlinked score output: {path}")
        key = path.resolve()
        need(self.saf in key.parents, f"Score output escapes the SAF attempt: {path}")
        need(key not in self.compared and key not in self.pending, f"Score output written twice: {path.name}")
        if key.exists():
            need(key.is_file() and key.read_bytes() == data, f"Regenerated bytes differ from the existing {key.name}")
            self.compared[key] = sha256_bytes(data)
        else:
            self.pending[key] = data
        return sha256_bytes(data)

    @contextlib.contextmanager
    def patched(self):
        from scripts.phase8.saf_surrogate import run as saf_run, score
        saved = (score.write_once, saf_run.write_once)
        score.write_once = saf_run.write_once = self.write
        try:
            yield self
        finally:
            score.write_once, saf_run.write_once = saved

    def commit(self):
        """Create only the never-written outputs, exclusively (xb); nothing existing can be replaced."""
        from scripts.phase8.saf_surrogate.registration import write_once
        for key, data in sorted(self.pending.items()):
            write_once(key, data)
        return {"byte_identical": sorted(self.relative(k) for k in self.compared),
                "created": sorted(self.relative(k) for k in self.pending)}

    def relative(self, key):
        return key.relative_to(self.saf).as_posix()


class OriginalIdentity:
    """The original bound identity; score_all reads only these two attributes to rebuild the reservation."""

    def __init__(self, identity, binary_sha256):
        self.identity, self.binary_sha256 = copy.deepcopy(identity), binary_sha256


class OriginalDataView:
    """Live context that answers generated-data identity questions with the original simulator identity.

    Everything else (root, lease, workers, source integrity) is the live current context. Used only to read
    the unchanged d/e producer proofs; the proofs themselves are still fully verified by the existing code.
    """

    def __init__(self, context, simulator, simulator_sha256):
        self._context = context
        self.simulator_identity, self.simulator_identity_sha256 = simulator, simulator_sha256

    def __getattr__(self, name):
        return getattr(self._context, name)


@contextlib.contextmanager
def bridged_command_specs(bridge, current_sources):
    """Child-process specs carry the original manifest sources; map only the authorized edit to its current hash."""
    from scripts.phase8.saf_surrogate import run as saf_run
    original = saf_run.command_spec

    def command_spec(*args, **kwargs):
        spec = original(*args, **kwargs)
        mapped = dict(spec["source_hashes"])
        for name in bridge["changed"]:
            if name in mapped:
                mapped[name] = current_sources[name]
        spec["source_hashes"] = mapped
        spec["operational_source_bridge"] = {key: bridge[key] for key in
                                              ("original_sources_sha256", "current_sources_sha256", "changed")}
        return spec

    saf_run.command_spec = command_spec
    try:
        yield
    finally:
        saf_run.command_spec = original


def copy_exact(source, destination):
    from scripts.phase8.pc_runtime import write_once
    data = Path(source).read_bytes()
    write_once(destination, data)
    need(sha256(destination) == sha256_bytes(data), f"Copy differs from the original: {source}")
    return sha256_bytes(data)


def make_workflow_class():
    from scripts.phase8 import python_pc
    from scripts.phase8.pc_runtime import write_once

    class RecoveryWorkflow(python_pc.ScientificWorkflow):
        def __init__(self, root, metadata, *, original, bridge, current_sources, **kwargs):
            super().__init__(root, metadata, **kwargs)
            self.original, self.bridge, self.current_sources = original, bridge, current_sources

        def f(self):
            from scripts.phase8.saf_surrogate.score import score_all
            context, run = self.owned("f", python_pc.REGISTRATIONS["saf"])
            try:
                bound = OriginalIdentity(self.original["identity"], self.original["reservation"]["binary_sha256"])
                resume = ExactResume(self.saf)
                with resume.patched():
                    scored = score_all(self.root, self.saf, self.reg["saf"], context.identity["registration_sha256"],
                                       bound, run, backend=self.backend)
                outcome = resume.commit()
                write_once(self.saf / "sole_score_summary.json", scored)
                verdict = "PASS" if all(scored[k] for k in ("fidelity_pass", "ranking_pass", "precision_pass")) else "FAIL"
                return self.finish(run, [self.saf], scientific_verdict=verdict, extra={"score_resume": outcome})
            except BaseException as exc:
                if not run._released:
                    run.release({"status": "ERROR", "exit_code": 1, "errors": [str(exc)], "outputs_complete": False})
                raise

        def g(self):
            from scripts.phase8.nozzle_ode import run as nozzle
            original = self.original["identity"]

            def source_loader(root, reg, context, out):
                view = OriginalDataView(context, original["simulator"], original["simulator_identity_sha256"])
                return python_pc.load_source_properties(root, reg, view, out)

            nozzle.run(self.root, context_factory=self.context_factory, source_loader=source_loader,
                       portable=True, backend=self.backend)
            terminal = python_pc.read_json(self.nozzle / "terminal.json")
            if terminal["status"] == "ERROR" or terminal.get("execution_complete") is not True \
                    or terminal.get("outputs_complete") is not True:
                raise RuntimeError("Nozzle execution did not complete: " + terminal["status"])
            return {"status": "COMPLETE", "execution_complete": True, "scientific_verdict": terminal["status"],
                    "artifacts": python_pc.artifacts(self.root, self.nozzle)}

        def h(self):
            with bridged_command_specs(self.bridge, self.current_sources):
                return super().h()

    return RecoveryWorkflow


# --------------------------------------------------------------------------- one-shot execution

def prepare_metadata(layout, original, bridge, git_info, config, new_sources):
    """Consumed marker first, then config, carried originals and the recovery record (all exclusive writes)."""
    from scripts.phase8.pc_runtime import write_once
    new = layout.new
    new.mkdir(parents=True, exist_ok=False)
    write_once(new / "recovery/consumed.json", {"schema": "pc-recovery-consumed-v1", "created_utc": utc(),
        "pid": os.getpid(), "argv": list(sys.argv), "source_commit": SOURCE_COMMIT, "head": git_info["head"]})
    write_once(new / "config.json", config.record())
    from scripts.pc_pipeline import describe as pipeline_describe
    write_once(new / "plan.json", pipeline_describe(config))
    copy_exact(layout.old / "parity20.json", new / "parity20.json")
    carried = {}
    for letter in CARRIED:
        carried[f"checkpoints/{letter}.json"] = copy_exact(layout.old / f"checkpoints/{letter}.json",
                                                           new / f"checkpoints/{letter}.json")
    for letter in "de":
        for name in ("reservation.json", "terminal.json", "released_lease.json"):
            carried[f"runs/{letter}/{name}"] = copy_exact(layout.old / f"runs/{letter}/{name}", new / f"runs/{letter}/{name}")
    evidence = {}
    for name in ("checkpoints/f.started.json", "runs/f/reservation.json", "runs/f/terminal.json", "runs/f/released_lease.json"):
        evidence[name] = copy_exact(layout.old / name, new / "recovery/original_f_attempt" / name.replace("/", "__"))
    for path in sorted((layout.old / "terminals").glob("*.json")):
        evidence[f"terminals/{path.name}"] = copy_exact(path, new / "recovery/original_f_attempt" / f"terminals__{path.name}")
    write_once(new / "recovery/original_metadata_manifest.json", original["old_manifest"])
    write_once(new / "recovery/preexisting_saf_manifest.json", original["saf_manifest"])
    record = {"schema": "pc-recovery-record-v1", "created_utc": utc(), "source_commit": SOURCE_COMMIT, "head": git_info["head"],
        "branch": BRANCH, "reason": "Stage f TypeError: Object of type bool is not JSON serializable (numpy.bool_ in named_metrics.json)",
        "authorization": "docs/plan.md exact user-approved recovery block 2026-10-05; reviewed operational clarification of the "
                         "registration's sole_score.crash_recovery exact-resume clause; the registration is not amended",
        "original_config_sha256": original["config_sha256"], "new_config_sha256": fingerprint(config.record()),
        "pinned_artifacts": original["pinned"], "original_identity": original["identity"],
        "source_mapping": {**bridge, "authorized_edits": {name: [[a, b] for a, b in edits] for name, edits in AUTHORIZED_EDITS.items()},
                           "script_sha256": new_sources[SELF_PATH]},
        "operational_mapping": "Generated data/producer proofs (stages d, e) keep the original python-v6 simulator identity and are "
                               "verified against it; stages f, g, h run under the live identity of the current sources, which are verified "
                               "against the original snapshot to differ only by the reviewed serialization fix and this script.",
        "carried_original_files_sha256": carried, "original_f_attempt_evidence_sha256": evidence,
        "carried_stages": list(CARRIED), "new_stages": list(NEW_STAGES),
        "original_f_attempt_seconds": original["original_f_attempt_seconds"]}
    write_once(new / "recovery/recovery_record.json", record)
    return record


def run_recovery(root, *, workflow_class=None, publish=None, new_sources=None, old_bytes=None, git=checked_git,
                 sleep_inhibitor=None, pins=None):
    """Verify, arm the one-attempt marker, then execute a, f, g, h, i once. Never retried."""
    from scripts.pc_pipeline import Config, publish_outputs, validate_checkpoint
    from scripts.phase8.pc_runtime import write_once
    from simulation.runtime import SleepInhibitor
    layout, original, bridge, git_info, current = verify_all(
        root, new_sources=new_sources, old_bytes=old_bytes, git=git, pins=pins)
    need(not git_info["run_blockers"], "Run blocked: " + "; ".join(git_info["run_blockers"]))
    for key in THREAD_ENV:
        need(os.environ.get(key) == "1", f"{key}=1 is required")
    config = Config(root=layout.root, workers=10, backend="torch", device="cpu", metadata_dir=Path(NEW_METADATA))
    new_sha = fingerprint(config.record())
    prepare_metadata(layout, original, bridge, git_info, config, current)
    os.environ["CATJET_SIMULATOR_BACKEND"] = "python"
    summary = {"status": "RUNNING", "started_utc": utc(), "recovery": True, "stages": [], "a2": "DEFERRED"}
    checkpoints = layout.new / "checkpoints"
    owner = {"owner_pid": os.getpid(), "config_sha256": new_sha, "started_utc": utc(), "argv": list(sys.argv)}
    write_once(layout.new / "owner.json", owner)
    active, completed = None, {letter: read_json(checkpoints / f"{letter}.json") for letter in CARRIED}
    try:
        workflow = (workflow_class or make_workflow_class())(layout.root, layout.new, original=original, bridge=bridge,
            current_sources=current, workers=config.workers, backend=config.backend, device=config.device)
        handlers = {letter: getattr(workflow, letter) for letter in "afgh"}
        handlers["i"] = (lambda: publish_outputs(config)) if publish is None else publish
        with (sleep_inhibitor or SleepInhibitor)() as inhibitor:
            summary["sleep_inhibition"] = inhibitor.metadata
            for letter in NEW_STAGES:
                active = letter
                for prior, receipt in completed.items():
                    validate_checkpoint(layout.root, receipt, original["config_sha256"] if prior in CARRIED else new_sha)
                started, before = utc(), time.perf_counter()
                write_once(checkpoints / f"{letter}.started.json", {"stage": letter, "started_utc": started, "owner": owner})
                result = handlers[letter]()
                if not isinstance(result, dict) or result.get("status") != "COMPLETE" or result.get("execution_complete") is not True:
                    raise RuntimeError(f"Stage {letter} did not complete: {result}")
                elapsed = time.perf_counter() - before
                receipt = {**result, "stage": letter, "status": "COMPLETE", "config_sha256": new_sha,
                           "started_utc": started, "finished_utc": utc(), "elapsed_seconds": elapsed}
                if letter == "f":
                    # Stage h charges the actually incurred f cost: the consumed first attempt plus this resume.
                    receipt.update(elapsed_seconds=elapsed + original["original_f_attempt_seconds"],
                                   recovery_elapsed_seconds=elapsed,
                                   original_attempt_elapsed_seconds=original["original_f_attempt_seconds"])
                validate_checkpoint(layout.root, receipt, new_sha)
                write_once(checkpoints / f"{letter}.json", receipt)
                completed[letter] = receipt
                summary["stages"].append({"stage": letter, "scientific_verdict": receipt.get("scientific_verdict")})
                if letter == "f":
                    verify_unchanged(layout.old, original["old_manifest"], exact=True)
                    verify_unchanged(layout.saf, original["saf_manifest"], exact=False)
            verdicts = {r.get("scientific_verdict") for r in completed.values()}
            summary.update(status="COMPLETE", scientific_verdict="FAIL" if "FAIL" in verdicts else
                           "INCOMPLETE" if verdicts & {"BLOCKED", "INCOMPLETE"} else "PASS")
        verify_unchanged(layout.old, original["old_manifest"], exact=True)
        verify_unchanged(layout.saf, original["saf_manifest"], exact=False)
    except BaseException as exc:
        summary.update(status="ERROR", stopped_at=active, error=f"{type(exc).__name__}: {exc}", traceback=traceback.format_exc())
    finally:
        summary["finished_utc"] = utc()
        write_once(layout.new / "terminals" / (uuid.uuid4().hex + ".json"), summary)
        if (layout.new / "owner.json").exists() and read_json(layout.new / "owner.json") == owner:
            (layout.new / "owner.json").unlink()
    summary["recovery_record_sha256"] = sha256(layout.new / "recovery/recovery_record.json")
    return summary


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true", help="verify only (default); writes nothing")
    mode.add_argument("--run", action="store_true", help="execute the one-shot recovery")
    args = parser.parse_args(argv)
    try:
        if args.run:
            result = run_recovery(ROOT)
            print(json.dumps(result, indent=2, allow_nan=False))
            return 0 if result["status"] == "COMPLETE" else 1
        layout, original, bridge, git_info, _ = verify_all(ROOT)
        print(json.dumps(describe(layout, original, bridge, git_info), indent=2, allow_nan=False))
        return 0
    except Exception as exc:
        print(json.dumps({"status": "ERROR", "error": f"{type(exc).__name__}: {exc}"}, indent=2), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
