#!/usr/bin/env python3
"""One-shot, integrity-first recovery of stages f-i after the stage-f JSON serialization crash.

Dry-run (default) verifies the consumed original attempt read-only and prints the intended actions.
``--run`` executes exactly once: it resumes the identical hashed score reservation, byte-compares every
existing score output against exactly regenerated bytes, then runs the actual pipeline stages g, h and i
into a NEW metadata directory. Nothing here changes a metric, threshold, model, selection or registration.

``--timing-publish-only`` is the separate, user-authorized continuation after that recovery ended with the
nozzle FAIL at stage g: it never touches f or g, verifies every retained tree read-only, and runs only the
unchanged stage h (timing + break-even) and stage i (publication) once into a fresh metadata directory.
"""
from __future__ import annotations

import argparse
import contextlib
import copy
import hashlib
import json
import os
import subprocess
import sys
import time
import traceback
import uuid
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

SOURCE_COMMIT = "0d16bcc245e93172aa4b3749bccc877727ce950c"
BRANCH = "pc-recovery-20261005"
OLD_METADATA = "outputs/phase8/pc_python_pipeline"
NEW_METADATA = "outputs/phase8/pc_python_recovery_20261005"
SAF_REGISTRATION = "docs/phase8_saf_surrogate_registration.json"
FIX_PATH = "scripts/phase8/saf_surrogate/registration.py"
SELF_PATH = "scripts/phase8/pc_recover_f_to_i.py"
THREAD_ENV = ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "VECLIB_MAXIMUM_THREADS")

# The only reviewed source edit: byte-exact replacement applied to the original (source commit) file.
AUTHORIZED_EDITS = {FIX_PATH: ((
    'def json_bytes(value):\n'
    '    return (json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\\n").encode()\n',
    'def _native(value):\n'
    '    """NumPy scalars (e.g. numpy.bool_) become plain Python values; everything else stays rejected."""\n'
    '    import sys\n'
    '    numpy = sys.modules.get("numpy")\n'
    '    if numpy is not None and isinstance(value, numpy.generic):\n'
    '        return value.item()\n'
    '    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")\n'
    '\n'
    '\n'
    'def json_bytes(value):\n'
    '    return (json.dumps(value, indent=2, sort_keys=True, allow_nan=False, default=_native) + "\\n").encode()\n'),)}
ALLOWED_CHANGES = frozenset({FIX_PATH, SELF_PATH, "tests/test_phase8_pc_recovery.py", "docs/FIXES.md", "docs/plan.md"})

# Independently captured immutable hashes of the consumed attempt (paths relative to the SAF attempt).
PINNED = {
    "score_reservation.json": "d03bfdc00d6383ff32787420ef64413a73b38c5f0a32b565340077f0ca937924",
    "predictions_freeze.json": "f8973dd677d667cc087274221beba43b14e7b2c450869805b39a775122a2dbbb",
    "selection.json": "6c76f8457fc588fd5da68715b5a391e27cf520a782bb48b903cc80466f1abb51",
    "test_metrics.json": "df550d78e0e781ae5a1b82f66e37326e94b10c1113f93789ee83c83ddc7422b6",
    "ranking_metrics.json": "26ef11f4af2554f6cfd3a458f9f34838563819de25b8148ac85e2611f3a83564",
}
SEALED_TARGETS = ("sealed/test_teacher_rows.csv", "sealed/test_teacher_species.npz", "sealed/ranking_teacher_rows.csv",
                  "sealed/ranking_teacher_species.npz", "sealed/named_central_full_state.csv", "sealed/named_central_species.npz")
# Outputs that only a completed f/h would create; their presence means this is not the crashed state.
MUST_BE_ABSENT = ("named_metrics.json", "sole_score_summary.json", "ranking_predictions.csv", "test_predictions.csv",
                  "named_predictions.csv", "all_candidate_diagnostic_metrics.csv", "per_seed_metrics.csv",
                  "deployment_receipt.json", "timing.json", "pc_timing_break_even.json", "report.json",
                  "mlx_gpu_timing.json", "pc_pipeline_provenance.json", "study_predictions.csv", "study_bands.csv",
                  "study_topten.json")
CARRIED = "bcde"
NEW_STAGES = "afghi"
OWNER_CMDLINES = ("pc_pipeline.py", "pc_recover_f_to_i.py")

# h/i-only continuation after the recorded nozzle FAIL (user-authorized 2026-10-05).
FIRST_RECOVERY_COMMIT = "3af5cc879b7916bbe9b21074030d065b2704f534"
TIMING_METADATA = "outputs/phase8/pc_python_timing_publish_20261005"
H_OUTPUTS = ("deployment_receipt.json", "timing.json", "pc_timing_break_even.json", "report.json", "mlx_gpu_timing.json",
             "pc_pipeline_provenance.json", "study_predictions.csv", "study_bands.csv", "study_topten.json")
H_RUNNER_PATHS = ("scripts/phase8/python_pc.py", "scripts/pc_pipeline.py")
MISSING_NOZZLE_OUTPUT = "source_property_coverage.json"
TIMING_STAGES = "hi"
KNOWN_G_ERROR = "RuntimeError: Nozzle execution did not complete: FAIL"


class RecoveryError(RuntimeError):
    pass


def need(condition, message):
    if not condition:
        raise RecoveryError(message)


def sha256(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def read_json(path):
    return json.loads(Path(path).read_text())


def fingerprint(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()).hexdigest()


def utc():
    return datetime.now(timezone.utc).isoformat()


class Layout:
    """Fixed locations of the consumed attempt and the new recovery metadata."""

    def __init__(self, root, *, old_metadata=OLD_METADATA, new_metadata=NEW_METADATA, registration=None):
        self.root = Path(root).resolve()
        self.old = self.root / old_metadata
        self.new = self.root / new_metadata
        reg = registration if registration is not None else read_json(self.root / SAF_REGISTRATION)
        self.registration = reg
        self.saf = self.root / reg["artifact_root"]

    def relative(self, path):
        return Path(path).resolve().relative_to(self.root).as_posix()


# --------------------------------------------------------------------------- read-only verification

def tree_manifest(folder):
    """sha256/size of every regular file; any symlink under the tree is rejected."""
    folder = Path(folder)
    need(folder.is_dir() and not folder.is_symlink(), f"Missing or symlinked tree: {folder}")
    result = {}
    for directory, dirs, files in os.walk(folder, followlinks=False):
        for name in (*dirs, *files):
            need(not os.path.islink(os.path.join(directory, name)), f"Symlink in consumed tree: {name}")
        for name in files:
            path = Path(directory) / name
            result[path.relative_to(folder).as_posix()] = {"sha256": sha256(path), "size": path.stat().st_size}
    return result


def verify_unchanged(folder, manifest, *, exact):
    """Original bytes and names survive; ``exact`` also forbids any added file."""
    current = tree_manifest(folder)
    missing = sorted(set(manifest) - set(current))
    changed = sorted(name for name in manifest if name in current and current[name] != manifest[name])
    added = sorted(set(current) - set(manifest))
    need(not missing and not changed, f"Consumed files changed or vanished: {(missing + changed)[:5]}")
    need(not (exact and added), f"Unexpected files added to the consumed tree: {added[:5]}")
    return {"files": len(manifest), "added": added}


def active_owner_processes(proc="/proc", *, own_pid=None):
    """Other live pipeline/recovery interpreters; argv-based so a shell that merely names the script is ignored."""
    own_pid = os.getpid() if own_pid is None else own_pid
    found = []
    proc = Path(proc)
    if not proc.is_dir():
        return found
    for entry in proc.iterdir():
        if not entry.name.isdigit() or int(entry.name) == own_pid:
            continue
        try:
            argv = (entry / "cmdline").read_bytes().split(b"\0")
        except OSError:
            continue
        argv = [part.decode(errors="replace") for part in argv if part]
        if argv and Path(argv[0]).name.startswith("python") and any(
                Path(part).name in OWNER_CMDLINES for part in argv[1:3]):
            found.append(int(entry.name))
    return found


def verify_sources(old_sources, new_sources, *, old_bytes, edits=AUTHORIZED_EDITS, self_path=SELF_PATH):
    """Only the reviewed fix (exact content) and this additive script may differ from the original snapshot."""
    added = sorted(set(new_sources) - set(old_sources))
    removed = sorted(set(old_sources) - set(new_sources))
    changed = sorted(name for name in old_sources if name in new_sources and old_sources[name] != new_sources[name])
    need(added == [self_path], f"Source additions other than the recovery script: {added}")
    need(not removed, f"Source files removed since the original snapshot: {removed}")
    need(changed == sorted(edits), f"Unauthorized source drift: {changed}")
    for name, replacements in edits.items():
        original = old_bytes(name)
        need(sha256_bytes(original) == old_sources[name], f"Source commit content differs from the recorded snapshot: {name}")
        expected = original
        for before, after in replacements:
            need(expected.count(before.encode()) == 1, f"Authorized edit anchor is not unique: {name}")
            expected = expected.replace(before.encode(), after.encode())
        need(sha256_bytes(expected) == new_sources[name], f"{name} is not exactly the authorized serialization fix")
    return {"added": added, "changed": changed, "removed": removed,
            "mapping": {name: {"original_sha256": old_sources[name], "current_sha256": new_sources[name]} for name in changed},
            "original_sources_sha256": fingerprint(old_sources), "current_sources_sha256": fingerprint(new_sources)}


def checked_git(root, *args):
    result = subprocess.run(["git", *args], cwd=root, capture_output=True, text=True)
    if result.returncode:
        raise RecoveryError(f"git {' '.join(args[:2])} failed: {result.stderr.strip()}")
    return result.stdout.strip()


def git_blob(root, commit, path):
    result = subprocess.run(["git", "show", f"{commit}:{path}"], cwd=root, capture_output=True)
    need(result.returncode == 0, f"Source commit does not contain {path}")
    return result.stdout


def verify_git(root, *, git=checked_git, source_commit=SOURCE_COMMIT, branch=BRANCH, allowed=ALLOWED_CHANGES):
    """Known source commit; every change since it is on the exact authorized file list."""
    need(git(root, "cat-file", "-t", source_commit) == "commit", "Known source commit is absent")
    head = git(root, "rev-parse", "HEAD")
    try:
        git(root, "merge-base", "--is-ancestor", source_commit, "HEAD")
    except RecoveryError:
        raise RecoveryError("HEAD does not descend from the known source commit") from None
    changed = set(git(root, "diff", "--name-only", source_commit).splitlines())
    untracked = {name for name in git(root, "ls-files", "--others", "--exclude-standard").splitlines()
                 if not name.startswith("outputs/")}
    unauthorized = sorted((changed | untracked) - set(allowed))
    need(not unauthorized, f"Changes outside the authorized file list: {unauthorized[:8]}")
    blockers = []
    if git(root, "branch", "--show-current") != branch:
        blockers.append(f"not on branch {branch}")
    if git(root, "status", "--porcelain", "--untracked-files=no"):
        blockers.append("tracked changes are uncommitted; commit the authorized files first")
    if git(root, "diff", "--cached", "--name-only"):
        blockers.append("staged files present (publication refuses them)")
    return {"head": head, "source_commit": source_commit, "changed_since_source": sorted(changed),
            "untracked_outside_outputs": sorted(untracked), "run_blockers": blockers}


def _owned(root, name):
    relative = Path(name)
    need(not relative.is_absolute() and ".." not in relative.parts, f"Escaped path: {name}")
    path = root / relative
    need(not path.is_symlink() and path.resolve().is_relative_to(root) and path.is_file(), f"Missing/symlinked/escaped file: {name}")
    return path


def verify_sealed_score(layout, pins, verify_artifacts):
    """Pinned score artifacts, reservation targets, frozen predictions/weights and bound original identity."""
    root, saf, old = layout.root, layout.saf, layout.old
    # Immutable pins and the reservation.
    pinned = {}
    for name, expected in pins.items():
        need(sha256(_owned(root, layout.relative(saf / name))) == expected, f"Pinned artifact changed: {name}")
        pinned[name] = expected
    reservation = read_json(saf / "score_reservation.json")
    reg_sha = sha256(root / SAF_REGISTRATION)
    need(reservation["registration_sha256"] == reg_sha, "Reservation registration differs")
    need(reservation["predictions_freeze_sha256"] == pins["predictions_freeze.json"]
         and reservation["selection_sha256"] == pins["selection.json"], "Reservation does not bind the pinned freeze/selection")
    expected_targets = {layout.relative(saf / name) for name in SEALED_TARGETS} | set(layout.registration["sole_score"]["named_paths"])
    need(set(reservation["targets"]) == expected_targets, "Reservation target set differs from the registered targets")
    for name, expected in reservation["targets"].items():
        need(sha256(_owned(root, name)) == expected, f"Reservation target changed: {name}")
    frozen = read_json(saf / "predictions_freeze.json")
    need(len(frozen["predictions"]) == 72 and len(frozen["weights"]) == 24, "Frozen prediction/weight counts differ")
    for key in ("predictions", "weights", "inputs"):
        verify_artifacts(saf, frozen[key])
    need(frozen["selection_sha256"] == pins["selection.json"] and frozen["registration_sha256"] == reg_sha
         and frozen["validation_sha256"] == sha256(saf / "validation.json"), "Prediction freeze bindings changed")
    # Identity: reservation, f reservation and the completed d/e producers all agree and match the source snapshot.
    identity = reservation["identity"]
    old_sources = read_json(old / "scientific_sources.json")
    need(identity["git_head"] == SOURCE_COMMIT and identity["registration_sha256"] == reg_sha, "Foreign original identity")
    need(read_json(old / "runs/f/reservation.json")["identity"] == identity, "Original f lease identity differs")
    for letter in "de":
        need(read_json(old / f"runs/{letter}/terminal.json")["identity"] == identity, f"Original {letter} producer identity differs")
    simulator = identity["simulator"]
    need(fingerprint(simulator) == identity["simulator_identity_sha256"] and simulator["source_hashes"] == old_sources
         and identity["source_hashes"] == old_sources, "Original identity does not match the recorded source snapshot")
    for name in ("generation_terminal.json", "product.json"):
        need(read_json(saf / name).get("simulator_identity_sha256") == identity["simulator_identity_sha256"],
             f"{name} was produced by another simulator identity")
    return {"pinned": pinned, "reservation": reservation, "identity": identity, "old_sources": old_sources,
            "registration_sha256": reg_sha}


def verify_original(layout, *, pins=None, validate_checkpoint=None, verify_artifacts=None):
    """Integrity of the consumed attempt; opens no score/metric content."""
    pins = PINNED if pins is None else pins
    if validate_checkpoint is None or verify_artifacts is None:
        from scripts.pc_pipeline import validate_checkpoint as default_checkpoint
        from scripts.phase8.saf_surrogate.registration import verify_artifacts as default_artifacts
        validate_checkpoint, verify_artifacts = validate_checkpoint or default_checkpoint, verify_artifacts or default_artifacts
    root, saf, old = layout.root, layout.saf, layout.old
    need(old.is_dir() and not old.is_symlink() and saf.is_dir() and not saf.is_symlink(), "Original attempt directories are missing")
    need(not layout.new.exists(), "A recovery attempt already exists; recovery is one-shot")
    for name in ("owner.json", "stage_owner.json", "publication_intent.json", "latest_terminal.json"):
        need(not (old / name).exists(), f"Active or unexpected owner record in the original metadata: {name}")
    need(not active_owner_processes(), "Another pipeline/recovery process is active")
    old_manifest, saf_manifest = tree_manifest(old), tree_manifest(saf)
    for name in MUST_BE_ABSENT:
        need(name not in saf_manifest, f"Unexpected scientific output exists: {name}")
    from scripts.pc_pipeline import scientific_outputs
    need(not scientific_outputs(root)["nozzle"].exists(), "Nozzle output already exists")
    # Stage state: a-e complete, f consumed without a receipt, nothing later.
    checkpoints = old / "checkpoints"
    config_sha = fingerprint(read_json(old / "config.json"))
    receipts = {}
    for letter in "abcde":
        receipts[letter] = validate_checkpoint(root, read_json(checkpoints / f"{letter}.json"), config_sha)
    need((checkpoints / "f.started.json").is_file() and not (checkpoints / "f.json").exists(), "Stage f is not in the crashed state")
    for letter in "ghi":
        need(not (checkpoints / f"{letter}.json").exists() and not (checkpoints / f"{letter}.started.json").exists(),
             f"Stage {letter} already started")
    terminal = read_json(old / "runs/f/terminal.json")
    need(terminal.get("status") == "ERROR" and any("not JSON serializable" in e for e in terminal.get("errors", [])),
         "Original stage f did not end with the diagnosed serialization error")
    sealed = verify_sealed_score(layout, pins, verify_artifacts)
    pinned, reservation, identity, old_sources = (sealed[k] for k in ("pinned", "reservation", "identity", "old_sources"))
    started = datetime.fromisoformat(read_json(checkpoints / "f.started.json")["started_utc"])
    spent = (datetime.fromisoformat(terminal["ended_utc"]) - started).total_seconds()
    need(spent > 0, "Original stage f elapsed time is not positive")
    return {"config_sha256": config_sha, "checkpoints": {k: v["config_sha256"] for k, v in receipts.items()},
            "pinned": pinned, "reservation_targets": len(reservation["targets"]), "frozen_predictions": 72,
            "frozen_weights": 24, "identity": identity, "reservation": reservation, "old_sources": old_sources,
            "original_f_attempt_seconds": spent, "old_manifest": old_manifest, "saf_manifest": saf_manifest}


def verify_all(root, *, new_sources=None, old_bytes=None, git=checked_git, pins=None):
    layout = Layout(root)
    original = verify_original(layout, pins=pins)
    if new_sources is None:
        from scripts.phase8.pc_python_runtime import source_hashes
        new_sources = source_hashes(layout.root)
    bridge = verify_sources(original["old_sources"], new_sources,
                            old_bytes=old_bytes or (lambda name: git_blob(layout.root, SOURCE_COMMIT, name)))
    return layout, original, bridge, verify_git(layout.root, git=git), new_sources


def describe(layout, original, bridge, git_info):
    """Verification summary and intended actions; deliberately free of any score content."""
    return {"mode": "dry-run", "status": "VERIFIED", "source_commit": SOURCE_COMMIT, "head": git_info["head"],
            "run_ready": not git_info["run_blockers"], "run_blockers": git_info["run_blockers"],
            "original_metadata": layout.relative(layout.old), "saf_attempt": layout.relative(layout.saf),
            "new_metadata_would_be": layout.relative(layout.new), "new_metadata_exists": layout.new.exists(),
            "original_config_sha256": original["config_sha256"], "verified_checkpoints": sorted(original["checkpoints"]),
            "pinned_artifacts": original["pinned"], "reservation_targets_verified": original["reservation_targets"],
            "frozen_predictions_verified": original["frozen_predictions"], "frozen_weights_verified": original["frozen_weights"],
            "original_identity_sha256": fingerprint(original["identity"]),
            "original_simulator_identity_sha256": original["identity"]["simulator_identity_sha256"],
            "original_metadata_files": len(original["old_manifest"]), "preexisting_saf_files": len(original["saf_manifest"]),
            "source_bridge": {key: bridge[key] for key in ("added", "changed", "removed", "original_sources_sha256",
                                                          "current_sources_sha256")},
            "changed_since_source_commit": git_info["changed_since_source"],
            "intended_actions": [
                "exclusively create the new metadata directory and the durable consumed marker (any later --run refuses)",
                "write the recovery record, source mapping and preexisting-file manifests; carry original b-e receipts and d/e producer proofs byte-identically",
                "stage a: record the NEW source snapshot and environment",
                "stage f: resume the identical reservation; score_all must regenerate existing outputs byte-for-byte or stop; no new reservation, prediction or weight is written",
                "stages g, h, i via the existing ScientificWorkflow/publish_outputs with the verified source bridge",
                "re-verify the original metadata tree and preexisting SAF files are byte-identical",
            ]}


# --------------------------------------------------------------------------- exact score resume

class ExactResume:
    """Writer adapter for score_all: existing files must match regenerated bytes; new files are held until all do."""

    def __init__(self, saf):
        self.saf = Path(saf).resolve()
        self.compared, self.pending = {}, {}

    def write(self, path, value):
        from scripts.phase8.saf_surrogate.registration import json_bytes
        data = value if isinstance(value, bytes) else json_bytes(value)
        path = Path(path)
        need(not path.is_symlink(), f"Symlinked score output: {path}")
        key = path.resolve()
        need(self.saf in key.parents, f"Score output escapes the SAF attempt: {path}")
        need(key not in self.compared and key not in self.pending, f"Score output written twice: {path.name}")
        if key.exists():
            need(key.is_file() and key.read_bytes() == data, f"Regenerated bytes differ from the existing {key.name}")
            self.compared[key] = sha256_bytes(data)
        else:
            self.pending[key] = data
        return sha256_bytes(data)

    @contextlib.contextmanager
    def patched(self):
        from scripts.phase8.saf_surrogate import run as saf_run, score
        saved = (score.write_once, saf_run.write_once)
        score.write_once = saf_run.write_once = self.write
        try:
            yield self
        finally:
            score.write_once, saf_run.write_once = saved

    def commit(self):
        """Create only the never-written outputs, exclusively (xb); nothing existing can be replaced."""
        from scripts.phase8.saf_surrogate.registration import write_once
        for key, data in sorted(self.pending.items()):
            write_once(key, data)
        return {"byte_identical": sorted(self.relative(k) for k in self.compared),
                "created": sorted(self.relative(k) for k in self.pending)}

    def relative(self, key):
        return key.relative_to(self.saf).as_posix()


class OriginalIdentity:
    """The original bound identity; score_all reads only these two attributes to rebuild the reservation."""

    def __init__(self, identity, binary_sha256):
        self.identity, self.binary_sha256 = copy.deepcopy(identity), binary_sha256


class OriginalDataView:
    """Live context that answers generated-data identity questions with the original simulator identity.

    Everything else (root, lease, workers, source integrity) is the live current context. Used only to read
    the unchanged d/e producer proofs; the proofs themselves are still fully verified by the existing code.
    """

    def __init__(self, context, simulator, simulator_sha256):
        self._context = context
        self.simulator_identity, self.simulator_identity_sha256 = simulator, simulator_sha256

    def __getattr__(self, name):
        return getattr(self._context, name)


@contextlib.contextmanager
def bridged_command_specs(bridge, current_sources):
    """Child-process specs carry the original manifest sources; map only the authorized edit to its current hash."""
    from scripts.phase8.saf_surrogate import run as saf_run
    original = saf_run.command_spec

    def command_spec(*args, **kwargs):
        spec = original(*args, **kwargs)
        mapped = dict(spec["source_hashes"])
        for name in bridge["changed"]:
            if name in mapped:
                mapped[name] = current_sources[name]
        spec["source_hashes"] = mapped
        spec["operational_source_bridge"] = {key: bridge[key] for key in
                                              ("original_sources_sha256", "current_sources_sha256", "changed")}
        return spec

    saf_run.command_spec = command_spec
    try:
        yield
    finally:
        saf_run.command_spec = original


def copy_exact(source, destination):
    from scripts.phase8.pc_runtime import write_once
    data = Path(source).read_bytes()
    write_once(destination, data)
    need(sha256(destination) == sha256_bytes(data), f"Copy differs from the original: {source}")
    return sha256_bytes(data)


def make_workflow_class():
    from scripts.phase8 import python_pc
    from scripts.phase8.pc_runtime import write_once

    class RecoveryWorkflow(python_pc.ScientificWorkflow):
        def __init__(self, root, metadata, *, original, bridge, current_sources, **kwargs):
            super().__init__(root, metadata, **kwargs)
            self.original, self.bridge, self.current_sources = original, bridge, current_sources

        def f(self):
            from scripts.phase8.saf_surrogate.score import score_all
            context, run = self.owned("f", python_pc.REGISTRATIONS["saf"])
            try:
                bound = OriginalIdentity(self.original["identity"], self.original["reservation"]["binary_sha256"])
                resume = ExactResume(self.saf)
                with resume.patched():
                    scored = score_all(self.root, self.saf, self.reg["saf"], context.identity["registration_sha256"],
                                       bound, run, backend=self.backend)
                outcome = resume.commit()
                write_once(self.saf / "sole_score_summary.json", scored)
                verdict = "PASS" if all(scored[k] for k in ("fidelity_pass", "ranking_pass", "precision_pass")) else "FAIL"
                return self.finish(run, [self.saf], scientific_verdict=verdict, extra={"score_resume": outcome})
            except BaseException as exc:
                if not run._released:
                    run.release({"status": "ERROR", "exit_code": 1, "errors": [str(exc)], "outputs_complete": False})
                raise

        def g(self):
            from scripts.phase8.nozzle_ode import run as nozzle
            original = self.original["identity"]

            def source_loader(root, reg, context, out):
                view = OriginalDataView(context, original["simulator"], original["simulator_identity_sha256"])
                return python_pc.load_source_properties(root, reg, view, out)

            nozzle.run(self.root, context_factory=self.context_factory, source_loader=source_loader,
                       portable=True, backend=self.backend)
            terminal = python_pc.read_json(self.nozzle / "terminal.json")
            if terminal["status"] == "ERROR" or terminal.get("execution_complete") is not True \
                    or terminal.get("outputs_complete") is not True:
                raise RuntimeError("Nozzle execution did not complete: " + terminal["status"])
            return {"status": "COMPLETE", "execution_complete": True, "scientific_verdict": terminal["status"],
                    "artifacts": python_pc.artifacts(self.root, self.nozzle)}

        def h(self):
            with bridged_command_specs(self.bridge, self.current_sources):
                return super().h()

    return RecoveryWorkflow


# --------------------------------------------------------------------------- one-shot execution

def prepare_metadata(layout, original, bridge, git_info, config, new_sources):
    """Consumed marker first, then config, carried originals and the recovery record (all exclusive writes)."""
    from scripts.phase8.pc_runtime import write_once
    new = layout.new
    new.mkdir(parents=True, exist_ok=False)
    write_once(new / "recovery/consumed.json", {"schema": "pc-recovery-consumed-v1", "created_utc": utc(),
        "pid": os.getpid(), "argv": list(sys.argv), "source_commit": SOURCE_COMMIT, "head": git_info["head"]})
    write_once(new / "config.json", config.record())
    from scripts.pc_pipeline import describe as pipeline_describe
    write_once(new / "plan.json", pipeline_describe(config))
    copy_exact(layout.old / "parity20.json", new / "parity20.json")
    carried = {}
    for letter in CARRIED:
        carried[f"checkpoints/{letter}.json"] = copy_exact(layout.old / f"checkpoints/{letter}.json",
                                                           new / f"checkpoints/{letter}.json")
    for letter in "de":
        for name in ("reservation.json", "terminal.json", "released_lease.json"):
            carried[f"runs/{letter}/{name}"] = copy_exact(layout.old / f"runs/{letter}/{name}", new / f"runs/{letter}/{name}")
    evidence = {}
    for name in ("checkpoints/f.started.json", "runs/f/reservation.json", "runs/f/terminal.json", "runs/f/released_lease.json"):
        evidence[name] = copy_exact(layout.old / name, new / "recovery/original_f_attempt" / name.replace("/", "__"))
    for path in sorted((layout.old / "terminals").glob("*.json")):
        evidence[f"terminals/{path.name}"] = copy_exact(path, new / "recovery/original_f_attempt" / f"terminals__{path.name}")
    write_once(new / "recovery/original_metadata_manifest.json", original["old_manifest"])
    write_once(new / "recovery/preexisting_saf_manifest.json", original["saf_manifest"])
    record = {"schema": "pc-recovery-record-v1", "created_utc": utc(), "source_commit": SOURCE_COMMIT, "head": git_info["head"],
        "branch": BRANCH, "reason": "Stage f TypeError: Object of type bool is not JSON serializable (numpy.bool_ in named_metrics.json)",
        "authorization": "docs/plan.md exact user-approved recovery block 2026-10-05; reviewed operational clarification of the "
                         "registration's sole_score.crash_recovery exact-resume clause; the registration is not amended",
        "original_config_sha256": original["config_sha256"], "new_config_sha256": fingerprint(config.record()),
        "pinned_artifacts": original["pinned"], "original_identity": original["identity"],
        "source_mapping": {**bridge, "authorized_edits": {name: [[a, b] for a, b in edits] for name, edits in AUTHORIZED_EDITS.items()},
                           "script_sha256": new_sources[SELF_PATH]},
        "operational_mapping": "Generated data/producer proofs (stages d, e) keep the original python-v6 simulator identity and are "
                               "verified against it; stages f, g, h run under the live identity of the current sources, which are verified "
                               "against the original snapshot to differ only by the reviewed serialization fix and this script.",
        "carried_original_files_sha256": carried, "original_f_attempt_evidence_sha256": evidence,
        "carried_stages": list(CARRIED), "new_stages": list(NEW_STAGES),
        "original_f_attempt_seconds": original["original_f_attempt_seconds"]}
    write_once(new / "recovery/recovery_record.json", record)
    return record


def run_recovery(root, *, workflow_class=None, publish=None, new_sources=None, old_bytes=None, git=checked_git,
                 sleep_inhibitor=None, pins=None):
    """Verify, arm the one-attempt marker, then execute a, f, g, h, i once. Never retried."""
    from scripts.pc_pipeline import Config, publish_outputs, validate_checkpoint
    from scripts.phase8.pc_runtime import write_once
    from simulation.runtime import SleepInhibitor
    layout, original, bridge, git_info, current = verify_all(
        root, new_sources=new_sources, old_bytes=old_bytes, git=git, pins=pins)
    need(not git_info["run_blockers"], "Run blocked: " + "; ".join(git_info["run_blockers"]))
    for key in THREAD_ENV:
        need(os.environ.get(key) == "1", f"{key}=1 is required")
    config = Config(root=layout.root, workers=10, backend="torch", device="cpu", metadata_dir=Path(NEW_METADATA))
    new_sha = fingerprint(config.record())
    prepare_metadata(layout, original, bridge, git_info, config, current)
    os.environ["CATJET_SIMULATOR_BACKEND"] = "python"
    summary = {"status": "RUNNING", "started_utc": utc(), "recovery": True, "stages": [], "a2": "DEFERRED"}
    checkpoints = layout.new / "checkpoints"
    owner = {"owner_pid": os.getpid(), "config_sha256": new_sha, "started_utc": utc(), "argv": list(sys.argv)}
    write_once(layout.new / "owner.json", owner)
    active, completed = None, {letter: read_json(checkpoints / f"{letter}.json") for letter in CARRIED}
    try:
        workflow = (workflow_class or make_workflow_class())(layout.root, layout.new, original=original, bridge=bridge,
            current_sources=current, workers=config.workers, backend=config.backend, device=config.device)
        handlers = {letter: getattr(workflow, letter) for letter in "afgh"}
        handlers["i"] = (lambda: publish_outputs(config)) if publish is None else publish
        with (sleep_inhibitor or SleepInhibitor)() as inhibitor:
            summary["sleep_inhibition"] = inhibitor.metadata
            for letter in NEW_STAGES:
                active = letter
                for prior, receipt in completed.items():
                    validate_checkpoint(layout.root, receipt, original["config_sha256"] if prior in CARRIED else new_sha)
                started, before = utc(), time.perf_counter()
                write_once(checkpoints / f"{letter}.started.json", {"stage": letter, "started_utc": started, "owner": owner})
                result = handlers[letter]()
                if not isinstance(result, dict) or result.get("status") != "COMPLETE" or result.get("execution_complete") is not True:
                    raise RuntimeError(f"Stage {letter} did not complete: {result}")
                elapsed = time.perf_counter() - before
                receipt = {**result, "stage": letter, "status": "COMPLETE", "config_sha256": new_sha,
                           "started_utc": started, "finished_utc": utc(), "elapsed_seconds": elapsed}
                if letter == "f":
                    # Stage h charges the actually incurred f cost: the consumed first attempt plus this resume.
                    receipt.update(elapsed_seconds=elapsed + original["original_f_attempt_seconds"],
                                   recovery_elapsed_seconds=elapsed,
                                   original_attempt_elapsed_seconds=original["original_f_attempt_seconds"])
                validate_checkpoint(layout.root, receipt, new_sha)
                write_once(checkpoints / f"{letter}.json", receipt)
                completed[letter] = receipt
                summary["stages"].append({"stage": letter, "scientific_verdict": receipt.get("scientific_verdict")})
                if letter == "f":
                    verify_unchanged(layout.old, original["old_manifest"], exact=True)
                    verify_unchanged(layout.saf, original["saf_manifest"], exact=False)
            verdicts = {r.get("scientific_verdict") for r in completed.values()}
            summary.update(status="COMPLETE", scientific_verdict="FAIL" if "FAIL" in verdicts else
                           "INCOMPLETE" if verdicts & {"BLOCKED", "INCOMPLETE"} else "PASS")
        verify_unchanged(layout.old, original["old_manifest"], exact=True)
        verify_unchanged(layout.saf, original["saf_manifest"], exact=False)
    except BaseException as exc:
        summary.update(status="ERROR", stopped_at=active, error=f"{type(exc).__name__}: {exc}", traceback=traceback.format_exc())
    finally:
        summary["finished_utc"] = utc()
        write_once(layout.new / "terminals" / (uuid.uuid4().hex + ".json"), summary)
        if (layout.new / "owner.json").exists() and read_json(layout.new / "owner.json") == owner:
            (layout.new / "owner.json").unlink()
    summary["recovery_record_sha256"] = sha256(layout.new / "recovery/recovery_record.json")
    return summary


# --------------------------------------------------------------------------- h/i-only continuation

def first_recovery_terminal(first):
    """The single terminal summary of the first recovery: the known ERROR at stage g after a and f."""
    terminals = sorted((first / "terminals").glob("*.json"))
    need(len(terminals) == 1, "The first recovery must hold exactly one terminal summary")
    summary = read_json(terminals[0])
    need(summary.get("status") == "ERROR" and summary.get("stopped_at") == "g" and summary.get("error") == KNOWN_G_ERROR,
         "The first recovery did not end with the known nozzle ERROR at stage g")
    need([entry["stage"] for entry in summary.get("stages", [])] == ["a", "f"], "The first recovery completed stages other than a and f")
    return terminals[0], summary


def verify_nozzle(root, nozzle):
    """Sealed failed nozzle attempt: every recorded hash intact; only the coverage receipt is absent."""
    root, nozzle = Path(root), Path(nozzle)
    rel = nozzle.relative_to(root).as_posix()
    manifest = tree_manifest(nozzle)
    terminal = read_json(nozzle / "terminal.json")
    need(terminal.get("status") == "FAIL" and terminal.get("scientific_verdict") == "FAIL"
         and terminal.get("execution_complete") is False and terminal.get("outputs_complete") is False
         and terminal.get("errors") == [], "Nozzle terminal differs from the known FAIL/INCOMPLETE state")
    missing = sorted(name for name in terminal["expected_outputs"] if not (root / name).exists())
    need(missing == [f"{rel}/{MISSING_NOZZLE_OUTPUT}"], f"Nozzle outputs missing other than the known coverage file: {missing}")
    for name, expected in {**terminal["artifact_hashes"], **read_json(nozzle / "hashes.json")}.items():
        need(sha256(_owned(root, name)) == expected, f"Nozzle artifact changed: {name}")
    reservation = read_json(nozzle / "score_reservation.json")
    need(len(reservation["checkpoint_hashes"]) == 6, "Nozzle score reservation does not bind six frozen fits")
    for name, expected in reservation["checkpoint_hashes"].items():
        need(sha256(_owned(root, name)) == expected, f"Nozzle frozen fit changed: {name}")
    need(reservation["input_manifest_sha256"] == sha256(nozzle / "input_manifest.json"), "Nozzle input manifest binding changed")
    report = read_json(nozzle / "report.json")
    need(report.get("status") == "FAIL" and report.get("registered_status") is not None, "Nozzle report is not the recorded FAIL")
    return {"manifest": manifest, "terminal": {key: terminal[key] for key in ("status", "scientific_verdict", "execution_complete",
            "outputs_complete", "errors", "wall_s")}, "missing_outputs": missing, "frozen_fits": 6,
            "report_status": report["status"], "registered_status": report["registered_status"]}


def verify_continuation(root, *, new_sources=None, old_bytes=None, blob=None, git=checked_git, pins=None):
    """Read-only verification of everything the h/i-only continuation relies on; opens no score content."""
    from scripts.pc_pipeline import scientific_outputs, validate_checkpoint
    from scripts.phase8.saf_surrogate.registration import verify_artifacts
    layout = Layout(root)
    root, old, first, saf = layout.root, layout.old, layout.new, layout.saf
    timing = root / TIMING_METADATA
    need(not timing.exists(), "A timing/publication attempt already exists; the continuation is one-shot")
    need(old.is_dir() and first.is_dir() and saf.is_dir() and not (old.is_symlink() or first.is_symlink() or saf.is_symlink()),
         "Original, first-recovery or SAF directories are missing")
    need(not active_owner_processes(), "Another pipeline/recovery process is active")
    for folder in (old, first):
        for name in ("owner.json", "stage_owner.json", "publication_intent.json", "latest_terminal.json"):
            need(not (folder / name).exists(), f"Active or unexpected owner record in {layout.relative(folder)}: {name}")
    # Original attempt: a-e complete under their own configuration; f consumed without a receipt there; nothing later.
    old_config = fingerprint(read_json(old / "config.json"))
    old_receipts = {letter: validate_checkpoint(root, read_json(old / f"checkpoints/{letter}.json"), old_config) for letter in "abcde"}
    need((old / "checkpoints/f.started.json").is_file() and not (old / "checkpoints/f.json").exists(),
         "Original stage f is not in its recorded crashed state")
    for letter in "ghi":
        need(not any((old / f"checkpoints/{letter}{suffix}").exists() for suffix in (".json", ".started.json")),
             f"Original stage {letter} already started")
    original_f = read_json(old / "runs/f/terminal.json")
    need(original_f.get("status") == "ERROR" and any("not JSON serializable" in e for e in original_f.get("errors", [])),
         "Original stage f did not end with the diagnosed serialization error")
    sealed = verify_sealed_score(layout, PINNED if pins is None else pins, verify_artifacts)
    # First recovery: exactly the recorded a/f completion and the known ERROR at g; trees as recorded.
    first_manifest, old_manifest, saf_manifest = tree_manifest(first), tree_manifest(old), tree_manifest(saf)
    verify_unchanged(old, read_json(first / "recovery/original_metadata_manifest.json"), exact=True)
    verify_unchanged(saf, read_json(first / "recovery/preexisting_saf_manifest.json"), exact=False)
    first_config = fingerprint(read_json(first / "config.json"))
    first_receipts = {letter: validate_checkpoint(root, read_json(first / f"checkpoints/{letter}.json"), first_config) for letter in "af"}
    for letter in "bcde":
        need((first / f"checkpoints/{letter}.json").read_bytes() == (old / f"checkpoints/{letter}.json").read_bytes(),
             f"Carried checkpoint {letter} differs from the original")
    need((first / "checkpoints/g.started.json").is_file() and not (first / "checkpoints/g.json").exists(),
         "First recovery stage g is not in its recorded consumed-without-receipt state")
    for letter in TIMING_STAGES:
        need(not any((first / f"checkpoints/{letter}{suffix}").exists() for suffix in (".json", ".started.json"))
             and not (first / "runs" / letter).exists(), f"Stage {letter} already started in the first recovery")
    for name in H_OUTPUTS:
        need(name not in saf_manifest, f"Stage h output already exists: {name}")
    terminal_path, terminal = first_recovery_terminal(first)
    started = datetime.fromisoformat(read_json(first / "checkpoints/g.started.json")["started_utc"])
    g_seconds = (datetime.fromisoformat(terminal["finished_utc"]) - started).total_seconds()
    need(g_seconds > 0, "The failed nozzle attempt's elapsed time is not positive")
    nozzle = verify_nozzle(root, scientific_outputs(root)["nozzle"])
    # Sources: original snapshot -> reviewed fix + scripts only; first-recovery snapshot -> current differs by this script alone.
    if new_sources is None:
        from scripts.phase8.pc_python_runtime import source_hashes
        new_sources = source_hashes(root)
    old_bytes = old_bytes or (lambda name: git_blob(root, SOURCE_COMMIT, name))
    old_sources = sealed["old_sources"]
    bridge = verify_sources(old_sources, new_sources, old_bytes=old_bytes)
    for name in H_RUNNER_PATHS:
        need(name in old_sources and new_sources[name] == old_sources[name], f"Unchanged h/i runner source differs: {name}")
    first_sources = read_json(first / "scientific_sources.json")
    verify_sources(old_sources, first_sources, old_bytes=old_bytes)
    drift = sorted(name for name in set(first_sources) | set(new_sources) if first_sources.get(name) != new_sources.get(name))
    need(set(drift) <= {SELF_PATH}, f"Source drift since the first recovery snapshot beyond this script: {drift}")
    blob = blob or (lambda name: git_blob(root, FIRST_RECOVERY_COMMIT, name))
    need(sha256_bytes(blob(SELF_PATH)) == first_sources[SELF_PATH], "First recovery snapshot is not the first recovery commit's script")
    git_info = verify_git(root, git=git)
    need(git(root, "cat-file", "-t", FIRST_RECOVERY_COMMIT) == "commit", "First recovery commit is absent")
    try:
        git(root, "merge-base", "--is-ancestor", FIRST_RECOVERY_COMMIT, "HEAD")
    except RecoveryError:
        raise RecoveryError("HEAD does not descend from the first recovery commit") from None
    run_branch = "pc-run-" + datetime.now(timezone.utc).strftime("%Y%m%d")
    if git(root, "branch", "--list", run_branch):
        git_info["run_blockers"].append(f"local publication branch {run_branch} already exists")
    f_receipt = first_receipts["f"]
    costs = {"c": old_receipts["c"]["elapsed_seconds"], "d": old_receipts["d"]["elapsed_seconds"],
             "e": old_receipts["e"]["elapsed_seconds"], "f": f_receipt["elapsed_seconds"],
             "f_original_attempt": f_receipt.get("original_attempt_elapsed_seconds"),
             "f_recovery_resume": f_receipt.get("recovery_elapsed_seconds"), "g_failed_attempt": g_seconds}
    return {"layout": layout, "timing": timing, "sealed": sealed, "bridge": bridge, "git": git_info, "new_sources": new_sources,
            "old_config_sha256": old_config, "first_config_sha256": first_config, "old_receipts": old_receipts,
            "first_receipts": first_receipts, "old_manifest": old_manifest, "first_manifest": first_manifest,
            "saf_manifest": saf_manifest, "nozzle": nozzle, "first_terminal_path": terminal_path, "first_terminal": terminal,
            "costs": costs, "run_branch": run_branch}


def describe_continuation(v):
    """Verification summary and intended actions of the h/i-only continuation; free of any score content."""
    layout, git_info, nozzle = v["layout"], v["git"], v["nozzle"]
    return {"mode": "timing-publish-only dry-run", "status": "VERIFIED", "source_commit": SOURCE_COMMIT,
            "first_recovery_commit": FIRST_RECOVERY_COMMIT, "head": git_info["head"],
            "run_ready": not git_info["run_blockers"], "run_blockers": git_info["run_blockers"],
            "stages": list(TIMING_STAGES), "f_g_handlers_called": False, "publication_branch_would_be": v["run_branch"],
            "original_metadata": layout.relative(layout.old), "first_recovery_metadata": layout.relative(layout.new),
            "saf_attempt": layout.relative(layout.saf), "new_metadata_would_be": TIMING_METADATA,
            "new_metadata_exists": v["timing"].exists(),
            "original_checkpoints_verified": sorted(v["old_receipts"]), "first_recovery_checkpoints_verified": sorted(v["first_receipts"]),
            "pinned_artifacts": v["sealed"]["pinned"], "reservation_targets_verified": len(v["sealed"]["reservation"]["targets"]),
            "original_metadata_files": len(v["old_manifest"]), "first_recovery_files": len(v["first_manifest"]),
            "preexisting_saf_files": len(v["saf_manifest"]), "nozzle_files": len(nozzle["manifest"]),
            "carried_f": {"scientific_verdict": v["first_receipts"]["f"].get("scientific_verdict")},
            "nozzle": {key: nozzle[key] for key in ("terminal", "missing_outputs", "frozen_fits", "report_status", "registered_status")},
            "setup_cost_seconds": v["costs"],
            "source_bridge": {key: v["bridge"][key] for key in ("added", "changed", "removed", "original_sources_sha256",
                                                               "current_sources_sha256")},
            "changed_since_source_commit": git_info["changed_since_source"],
            "intended_actions": [
                "exclusively create outputs/phase8/pc_python_timing_publish_20261005 and its durable consumed marker (any later --run refuses)",
                "carry original b-e and first-recovery f checkpoints/producer proofs byte-for-byte; record a cost-only INCOMPLETE g entry (never a completed g receipt)",
                "snapshot the current sources/environment (stage-a code) into the new metadata",
                "stage h: unchanged run_timing through the existing recovery h adapter; stage i: unchanged publish_outputs",
                "re-verify the original, first-recovery, nozzle and SAF trees before h, after h and after i; f/g are never run",
            ]}


def check_cost_only_g(entry):
    need(entry.get("status") == "INCOMPLETE" and entry.get("execution_complete") is False and entry.get("outputs_complete") is False
         and entry.get("scientific_verdict") == "FAIL" and entry.get("cost_only") is True, "Stage g entry is not the honest cost-only record")


def prepare_continuation_metadata(v, config, git_info, current_sources):
    """Consumed marker first, then config, carried originals, the cost-only g entry and the continuation record."""
    from scripts.phase8.pc_runtime import write_once
    layout, new, old, first = v["layout"], v["timing"], v["layout"].old, v["layout"].new
    new.mkdir(parents=True, exist_ok=False)
    write_once(new / "recovery/consumed.json", {"schema": "pc-timing-publish-consumed-v1", "created_utc": utc(), "pid": os.getpid(),
        "argv": list(sys.argv), "source_commit": SOURCE_COMMIT, "first_recovery_commit": FIRST_RECOVERY_COMMIT, "head": git_info["head"]})
    write_once(new / "config.json", config.record())
    from scripts.pc_pipeline import describe as pipeline_describe
    write_once(new / "plan.json", pipeline_describe(config))
    need(sha256(old / "parity20.json") == sha256(first / "parity20.json"), "Parity record differs between the original and first recovery")
    copy_exact(first / "parity20.json", new / "parity20.json")
    carried = {}
    for letter in CARRIED:
        carried[f"checkpoints/{letter}.json"] = copy_exact(old / f"checkpoints/{letter}.json", new / f"checkpoints/{letter}.json")
    carried["checkpoints/f.json"] = copy_exact(first / "checkpoints/f.json", new / "checkpoints/f.json")
    for letter, source in (("d", old), ("e", old), ("f", first)):
        for name in ("reservation.json", "terminal.json", "released_lease.json"):
            carried[f"runs/{letter}/{name}"] = copy_exact(source / f"runs/{letter}/{name}", new / f"runs/{letter}/{name}")
    evidence = {}
    for name in ("recovery/recovery_record.json", "recovery/consumed.json", "checkpoints/g.started.json", "config.json",
                 "checkpoints/a.json", v["first_terminal_path"].relative_to(first).as_posix()):
        evidence[name] = copy_exact(first / name, new / "recovery/first_recovery" / name.replace("/", "__"))
    from scripts.pc_pipeline import scientific_outputs
    nozzle = scientific_outputs(layout.root)["nozzle"]
    references = {"first_recovery_terminal": {"path": layout.relative(v["first_terminal_path"]), "sha256": sha256(v["first_terminal_path"])},
                  "first_recovery_g_started": {"path": layout.relative(first / "checkpoints/g.started.json"),
                                               "sha256": sha256(first / "checkpoints/g.started.json")},
                  "nozzle_terminal": {"path": layout.relative(nozzle / "terminal.json"), "sha256": sha256(nozzle / "terminal.json")},
                  "nozzle_report": {"path": layout.relative(nozzle / "report.json"), "sha256": sha256(nozzle / "report.json")},
                  "nozzle_hashes": {"path": layout.relative(nozzle / "hashes.json"), "sha256": sha256(nozzle / "hashes.json")}}
    started = read_json(first / "checkpoints/g.started.json")["started_utc"]
    g_entry = {"stage": "g", "status": "INCOMPLETE", "state": "INCOMPLETE", "cost_only": True, "execution_complete": False,
               "outputs_complete": False, "scientific_verdict": "FAIL", "elapsed_seconds": v["costs"]["g_failed_attempt"],
               "started_utc": started, "finished_utc": v["first_terminal"]["finished_utc"], "references": references,
               "missing_outputs": v["nozzle"]["missing_outputs"],
               "note": "Failed nozzle attempt kept as FAIL/INCOMPLETE. This is NOT a completed g checkpoint: it records the "
                       "actually incurred cost for the unchanged h setup arithmetic only and is excluded from validated stages."}
    check_cost_only_g(g_entry)
    write_once(new / "checkpoints/g.json", g_entry)
    write_once(new / "recovery/original_metadata_manifest.json", v["old_manifest"])
    write_once(new / "recovery/first_recovery_manifest.json", v["first_manifest"])
    write_once(new / "recovery/preexisting_saf_manifest.json", v["saf_manifest"])
    write_once(new / "recovery/nozzle_manifest.json", v["nozzle"]["manifest"])
    record = {"schema": "pc-timing-publish-record-v1", "created_utc": utc(), "source_commit": SOURCE_COMMIT,
        "first_recovery_commit": FIRST_RECOVERY_COMMIT, "head": git_info["head"], "branch": BRANCH,
        "authorization": "docs/plan.md 'Timing and publication after recorded nozzle FAIL' (user-authorized 2026-10-05): continue with "
                         "stages h and i only after the recorded nozzle FAIL; the standard pipeline completion gate for g is bypassed "
                         "only under this explicit instruction while the unchanged h runner is called directly through the existing h adapter",
        "original_config_sha256": v["old_config_sha256"], "first_recovery_config_sha256": v["first_config_sha256"],
        "new_config_sha256": fingerprint(config.record()), "pinned_artifacts": v["sealed"]["pinned"],
        "original_sources_sha256": v["bridge"]["original_sources_sha256"], "current_sources_sha256": v["bridge"]["current_sources_sha256"],
        "source_mapping": {key: v["bridge"][key] for key in ("added", "changed", "removed", "mapping")},
        "script_sha256": current_sources[SELF_PATH], "carried_stages": list(CARRIED) + ["f"], "timing_publish_stages": list(TIMING_STAGES),
        "carried_original_files_sha256": carried, "first_recovery_evidence_sha256": evidence,
        "carried_f": {"scientific_verdict": v["first_receipts"]["f"].get("scientific_verdict")},
        "nozzle": {key: v["nozzle"][key] for key in ("terminal", "missing_outputs", "frozen_fits", "report_status", "registered_status")},
        "cost_only_g_entry": g_entry, "setup_cost_seconds": v["costs"],
        "missing_nozzle_coverage_receipt": MISSING_NOZZLE_OUTPUT + " is deliberately not created; the nozzle result stays FAIL/INCOMPLETE",
        "deployment_validation": "product deployment validation versus changed source provenance is deferred to the freeze step"}
    write_once(new / "recovery/continuation_record.json", record)
    return record


def verify_retained(v, *, saf_exact):
    """Original, first-recovery and nozzle trees stay byte-identical; the SAF tree only gains legitimate h outputs."""
    layout = v["layout"]
    verify_unchanged(layout.old, v["old_manifest"], exact=True)
    verify_unchanged(layout.new, v["first_manifest"], exact=True)
    from scripts.pc_pipeline import scientific_outputs
    nozzle = scientific_outputs(layout.root)["nozzle"]
    verify_unchanged(nozzle, v["nozzle"]["manifest"], exact=True)
    need(not (nozzle / MISSING_NOZZLE_OUTPUT).exists(), "The absent nozzle coverage receipt must stay absent")
    return verify_unchanged(layout.saf, v["saf_manifest"], exact=saf_exact)


def run_timing_publish(root, *, workflow_class=None, publish=None, new_sources=None, old_bytes=None, blob=None, git=checked_git,
                       sleep_inhibitor=None, pins=None):
    """Verify, arm the one-attempt marker, then run only h and i once (preceded by the stage-a source snapshot)."""
    from scripts.pc_pipeline import Config, publish_outputs, validate_checkpoint
    from scripts.phase8.pc_runtime import write_once
    from simulation.runtime import SleepInhibitor
    v = verify_continuation(root, new_sources=new_sources, old_bytes=old_bytes, blob=blob, git=git, pins=pins)
    layout, timing, git_info = v["layout"], v["timing"], v["git"]
    need(not git_info["run_blockers"], "Run blocked: " + "; ".join(git_info["run_blockers"]))
    for key in THREAD_ENV:
        need(os.environ.get(key) == "1", f"{key}=1 is required")
    config = Config(root=layout.root, workers=10, backend="torch", device="cpu", metadata_dir=Path(TIMING_METADATA))
    new_sha = fingerprint(config.record())
    prepare_continuation_metadata(v, config, git_info, v["new_sources"])
    os.environ["CATJET_SIMULATOR_BACKEND"] = "python"
    summary = {"status": "RUNNING", "started_utc": utc(), "continuation": "timing-publish-only", "stages": [], "a2": "DEFERRED"}
    checkpoints = timing / "checkpoints"
    owner = {"owner_pid": os.getpid(), "config_sha256": new_sha, "started_utc": utc(), "argv": list(sys.argv)}
    write_once(timing / "owner.json", owner)
    shas = {**{letter: v["old_config_sha256"] for letter in CARRIED}, "f": v["first_config_sha256"]}
    completed, active = {letter: read_json(checkpoints / f"{letter}.json") for letter in (*CARRIED, "f")}, None
    try:
        workflow = (workflow_class or make_workflow_class())(layout.root, timing, original=v["sealed"], bridge=v["bridge"],
            current_sources=v["new_sources"], workers=config.workers, backend=config.backend, device=config.device)
        handlers = {"a": workflow.a, "h": workflow.h, "i": (lambda: publish_outputs(config)) if publish is None else publish}
        with (sleep_inhibitor or SleepInhibitor)() as inhibitor:
            summary["sleep_inhibition"] = inhibitor.metadata
            verify_retained(v, saf_exact=True)
            for letter in "a" + TIMING_STAGES:
                active = letter
                for prior, receipt in completed.items():
                    validate_checkpoint(layout.root, receipt, shas.get(prior, new_sha))
                check_cost_only_g(read_json(checkpoints / "g.json"))
                started, before = utc(), time.perf_counter()
                write_once(checkpoints / f"{letter}.started.json", {"stage": letter, "started_utc": started, "owner": owner})
                result = handlers[letter]()
                if not isinstance(result, dict) or result.get("status") != "COMPLETE" or result.get("execution_complete") is not True:
                    raise RuntimeError(f"Stage {letter} did not complete: {result}")
                receipt = {**result, "stage": letter, "status": "COMPLETE", "config_sha256": new_sha, "started_utc": started,
                           "finished_utc": utc(), "elapsed_seconds": time.perf_counter() - before}
                validate_checkpoint(layout.root, receipt, new_sha)
                write_once(checkpoints / f"{letter}.json", receipt)
                completed[letter] = receipt
                shas[letter] = new_sha
                summary["stages"].append({"stage": letter, "scientific_verdict": receipt.get("scientific_verdict")})
                if letter != "i":
                    verify_retained(v, saf_exact=letter == "a")
            summary["saf_files_added"] = verify_retained(v, saf_exact=False)["added"]
            summary.update(status="COMPLETE", publication={key: completed["i"].get(key) for key in ("branch", "commit")})
        # Carried results are reported regardless of the publication outcome.
        summary["carried"] = {"f": v["first_receipts"]["f"].get("scientific_verdict"),
                              "g": {"status": "INCOMPLETE", "scientific_verdict": "FAIL", "missing_outputs": v["nozzle"]["missing_outputs"]}}
        verdicts = {completed["f"].get("scientific_verdict"), "FAIL", completed["h"].get("scientific_verdict")}
        summary["scientific_verdict"] = "FAIL" if "FAIL" in verdicts else "INCOMPLETE" if verdicts & {"BLOCKED", "INCOMPLETE"} else "PASS"
    except BaseException as exc:
        summary.update(status="ERROR", stopped_at=active, error=f"{type(exc).__name__}: {exc}", traceback=traceback.format_exc())
    finally:
        summary["finished_utc"] = utc()
        write_once(timing / "terminals" / (uuid.uuid4().hex + ".json"), summary)
        if (timing / "owner.json").exists() and read_json(timing / "owner.json") == owner:
            (timing / "owner.json").unlink()
    summary["continuation_record_sha256"] = sha256(timing / "recovery/continuation_record.json")
    return summary


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true", help="verify only (default); writes nothing")
    mode.add_argument("--run", action="store_true", help="execute the one-shot recovery")
    parser.add_argument("--timing-publish-only", action="store_true",
                        help="h/i-only continuation after the recorded nozzle FAIL (never runs f or g); combine with --dry-run or --run")
    args = parser.parse_args(argv)
    try:
        if args.timing_publish_only:
            if args.run:
                result = run_timing_publish(ROOT)
                print(json.dumps(result, indent=2, allow_nan=False))
                return 0 if result["status"] == "COMPLETE" else 1
            print(json.dumps(describe_continuation(verify_continuation(ROOT)), indent=2, allow_nan=False))
            return 0
        if args.run:
            result = run_recovery(ROOT)
            print(json.dumps(result, indent=2, allow_nan=False))
            return 0 if result["status"] == "COMPLETE" else 1
        layout, original, bridge, git_info, _ = verify_all(ROOT)
        print(json.dumps(describe(layout, original, bridge, git_info), indent=2, allow_nan=False))
        return 0
    except Exception as exc:
        print(json.dumps({"status": "ERROR", "error": f"{type(exc).__name__}: {exc}"}, indent=2), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
